---
# tasks file for users

- name: Make sure we have a wheel group
  group:
    name: wheel
    state: present
- name: sudo without password for wheel group
  copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440
- name: Add new users
  user:
    name: "{{item.name}}"
    shell: /bin/bash
    state: present
    groups: wheel
    append: yes
  with_items: "{{user_details}}"
- name: Set authorized key taken from file
  authorized_key:
    user: "{{item.name}}"
    state: present
    key: "{{ lookup('file', item.file) }}"
  with_items: "{{user_details}}"
